name: Java Tests + Allure

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2
        with:
          # Можно добавить версии браузеров, если нужно
          browser: chrome
          # browserVersion: "128.0"   # раскомментируй, если хочешь фиксированную

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run tests
        run: |
          ./gradlew clean test --info \
            -Dselenide.remote=http://localhost:4444/wd/hub \
            -Dselenide.browser=chrome \
            -Dselenide.browserVersion=128.0 \
            -Dselenide.browserSize=1920x1080 \
            -Dselenide.pageLoadStrategy=eager \
            -Dselenide.baseUrl=${{ secrets.BASEURL }} \
            -DselenoidCredential=${{ secrets.SELENOIDCREDENTIAL }} \
            -DselenoidUrl=${{ secrets.SELENOIDURL }}

      # Публикация Allure отчёта
      - name: Publish Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history